version: "3.8"

services:
  server:
    container_name: fatafat-server
    restart: unless-stopped
    image: openai-production:2.0.0
    build:
      context: /fatafat-backend
      target: production
      dockerfile: Dockerfile
    ports:
      - 5000:5000
    environment:
      - NODE_ENV=production
    networks:
      - shared-network
  
networks:
  shared-network: