version: "3.8"

services:
  dashboard:
    container_name: dashboard
    restart: unless-stopped
    image: dashboard-production:1.0.0
    build:
      context: /fatafat-frontend
      target: Production
      dockerfile: Dockerfile
    ports:
      - 5173:5173
    networks:
      - shared-network
networks:
  shared-network: